# Generated by Django 4.2.4 on 2023-09-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="BUSINESS", max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="signature",
            field=models.CharField(default="AS ALWAYS - STAY FROSTY!", max_length=140),
        ),
    ]
