FROM python:3.11

# Set environment variables for your Django project (customize as needed)
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=your_project_name.settings


WORKDIR /app

COPY requirements.txt /app/

 # Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

 # Copy the current directory contents into the container at /app
COPY . /app/

EXPOSE 8000

 # Run app.py when the container launches
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]